name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup Rust
      run: rustup toolchain install nightly --profile minimal
    - name: Setup ZigBuild
      run: pip install cargo-zigbuild
    - uses: Swatinem/rust-cache@v2
    - name: Build
      run: cargo zigbuild -p jslt --verbose
    - name: Build NodeJS
      run: cargo zigbuild -p jslt-node --verbose
    - name: Run tests
      run: cargo test --verbose
