name: Rust

on:
  push:
    branches: [ "main", "poc" ]
  pull_request:
    branches: [ "main", "poc" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        target: [aarch64-apple-darwin, x86_64-apple-darwin, x86_64-unknown-linux-gnu, x86_64-pc-windows-gnu]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup Rust
      run: |
        rustup toolchain install nightly --profile minimal
        rustup target add ${{ matrix.target }}
    - name: Setup ZigBuild
      run: pip install cargo-zigbuild
    - uses: Swatinem/rust-cache@v2
    - name: Build
      run: cargo zigbuild --workspace --verbose --target ${{ matrix.target }}
    - name: Run tests
      run: cargo test --workspace --verbose
