name: Rust

on:
  push:
    branches: [ "main", "poc" ]
  pull_request:
    branches: [ "main", "poc" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup Rust
      run: rustup toolchain install nightly --profile minimal
    - uses: Swatinem/rust-cache@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
